language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm cache verify
  - npm run-script build
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: pokeact